### ISSUE TITLE
Arrows missing

### ISSUE THREAD

**Issue by thisislola** [inukshuk/sqleton#16]
Hi, 

Thank you for the great tool! I have tried every single layout, but none of them show the arrows as in the example. Then I downloaded the z.sqlite file and tested that and it worked without issue (showing arrows). 

I'm on a mac M1
npm -v: 9.4.2
Installed graphviz with brew

My example: 
<img width="795" alt="image" src="https://user-images.githubusercontent.com/22214795/217826969-6b6fd969-34d2-4b72-929f-ef6385821196.png">

**Comment by inukshuk** [comment]
Generally, it depends on your db. We fetch the foreign key constraints using [the `foreign_key_list` pragma statement](https://sqlite.org/pragma.html#pragma_foreign_key_list); if the constraints show up there, they should be included as edges in the graph.
