### ISSUE TITLE
containerized sqleton cannot find sqlite3 

### ISSUE THREAD

**Issue by aldobranti** [inukshuk/sqleton#17]
I have to run sqleton in Docker if I want to access a sqlite database in a NAS environment.

I have this Dockerfile
`FROM alpine:latest

RUN     apk add git
RUN     apk add graphviz
RUN     apk add nodejs npm
RUN     git clone https://github.com/inukshuk/sqleton.git
RUN     npm i sqlite3  -g`

build it `docker build . -t sqleton`
and execute at the linux shell
`docker run --rm -v/home:/home -v/srv:/srv -it sqleton sh`

in the container, I can check location of the dbms and then I would aim to enter a command like
`sqleton -L dot -e -o dot-thing.dot /home/pi/.home-assistant/home-assistant_v2.db`

but I have had problems, so I check out sqleton
`/ # /sqleton/bin/sqleton -h
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'sqlite3'
Require stack:
- /sqleton/bin/sqleton
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/sqleton/bin/sqleton:6:16)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/sqleton/bin/sqleton' ]
}

Node.js v18.18.2`

I am very ropy/out of date in JS programming so what is going on here?

**Comment by inukshuk** [comment]
Why do you clone the repository instead of installing it via npm?

**Comment by aldobranti** [comment]
Being of the meganube nature and knowing zilch about js and npm I did what
I thought was the standard way. I'll surely try it out and let you know.
And thanks for replying
A

**Comment by aldobranti** [comment]
OK -- having picked up some tips I have a working and containerised sqleton and a happy system manager
and for the record a working Dockerfile

`FROM alpine:latest
# docker run --rm -it -v/srv:/srv -v/home:/home sqleton
## sqleton -L dot -e -o dot-thing.dot /home/pi/.home-assistant/home-assistant_v2.db

run     mkdir /app
WORKDIR /app
                  # NB! obligatory use of WORKDIR 
RUN     apk add graphviz npm
RUN     npm install sqleton
CMD     /app/node_modules/sqleton/bin/sqleton -h`

adapt CMD to particular need && thanks for creating sqleton -- I now have an elegant graphviz of my Home Assitant db
