### ISSUE TITLE
SQL string literals must be single-quoted

### ISSUE THREAD

**Issue by t-voet** [inukshuk/sqleton#19]
Thanks for this handy tool!
I get this error, however:
`Error: SQLITE_ERROR: no such column: "table" - should this be a string literal in single-quotes?`
See https://www.sqlite.org/quirks.html#dblquote.
Swapping single- and double quotes on line 49 fixes this.

**Comment by inukshuk** [comment]
Thanks! Out of curiosity, what's your SQLite version?

**Comment by t-voet** [comment]
That would be SQLite 3.46.0; the latest release at time of writing.
Thanks for fixing!
